@host= https://localhost:7016
POST {{host}}/auth/register
Content-Type: application/json; charset=utf-8;

{
    "firstName":"Shifa",
    "lastName":"Alam",
    "email":"shifa.cse70@gmail.com",
    "password":"Alam123"
}